name: flutter_user_certificates_android
description: "A Flutter plugin to get the user CA certificates on Android."
version: 0.1.0
repository: https://github.com/johnstef99/flutter_user_certificates_android

environment:
  sdk: ^3.12.0
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.johnstef.flutter_user_certificates_android
        pluginClass: FlutterUserCertificatesAndroidPlugin
